level1 = [
    "WWWWWWWWWWWWWWWWWW",
    "WP         WWW   W",
    "WWWWWW WSW WWW W W",
    "WWW    WSW     W W",
    "W    WWWSWWWWW W W",
    "W WWKW     WWWSW W",
    "W WWWW WWW WWWSW W",
    "W  WWW W         W",
    "W  WWW W WWWW WW W",
    "WW WKW W WWWW WWWW",
    "WW     W WK      W",
    "WWWWWWWW WWWWWWWSW",
    "W                W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW   WW   WWWWW",
    "WWWWWDWWWWWWDWWWWW",
    "WWWWW        WWWWW",
    "WWWWWWWWEEWWWWWWWW",
]
level2 = [
    "WWWWWWWWWWWWWWWWWW",
    "W         WWWK   W",
    "WWWWWW W WKWWW W W",
    "WWW    W       W W",
    "W    WWWWWWWW  W W",
    "W WWWWWWWWWWWKW  W",
    "W WWWW    WWWWWW W",
    "W  WWWDWW W      W",
    "W  WWWDWEEWKW  W W",
    "WW WWWDWWWWWWWWW W",
    "WW     W         W",
    "WW WWWWW WWWWWWWWW",
    "WWKW             W",
    "WWWWW WWWWWW WWWWW",
    "WWWWW  WWWW  WWWWW",
    "W  W    WW    W KW",
    "WW    W    W    WW",
    "WWWWWWWW PWWWWWWWW",
]
levels=[level1, level2]
